In [4]:
import pandas as pd
import pyarrow.parquet as pq
import sklearn

In [5]:
pd.__version__

'1.4.2'

In [6]:
!pip install pyarrow

Requirement already satisfied: pyarrow in /home/codespace/anaconda3/lib/python3.9/site-packages (21.0.0)

In [7]:
df=pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-01.parquet')

In [8]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
0,1,2022-01-01 00:35:40,2022-01-01 00:53:29,2.0,3.80,1.0,N,142,236,1,14.5,3.0,0.5,3.65,0.0,0.3,21.95,2.5,0.0
1,1,2022-01-01 00:33:43,2022-01-01 00:42:07,1.0,2.10,1.0,N,236,42,1,8.0,0.5,0.5,4.00,0.0,0.3,13.30,0.0,0.0
2,2,2022-01-01 00:53:21,2022-01-01 01:02:19,1.0,0.97,1.0,N,166,166,1,7.5,0.5,0.5,1.76,0.0,0.3,10.56,0.0,0.0
3,2,2022-01-01 00:25:21,2022-01-01 00:35:23,1.0,1.09,1.0,N,114,68,2,8.0,0.5,0.5,0.00,0.0,0.3,11.80,2.5,0.0
4,2,2022-01-01 00:36:48,2022-01-01 01:14:20,1.0,4.30,1.0,N,68,163,1,23.5,0.5,0.5,3.00,0.0,0.3,30.30,2.5,0.0

In [9]:
df_jan2023=pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-01.parquet')

In [10]:
df_jan2023.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
0,2,2023-01-01 00:32:10,2023-01-01 00:40:36,1.0,0.97,1.0,N,161,141,2,9.3,1.00,0.5,0.00,0.0,1.0,14.30,2.5,0.00
1,2,2023-01-01 00:55:08,2023-01-01 01:01:27,1.0,1.10,1.0,N,43,237,1,7.9,1.00,0.5,4.00,0.0,1.0,16.90,2.5,0.00
2,2,2023-01-01 00:25:04,2023-01-01 00:37:49,1.0,2.51,1.0,N,48,238,1,14.9,1.00,0.5,15.00,0.0,1.0,34.90,2.5,0.00
3,1,2023-01-01 00:03:48,2023-01-01 00:13:25,0.0,1.90,1.0,N,138,7,1,12.1,7.25,0.5,0.00,0.0,1.0,20.85,0.0,1.25
4,2,2023-01-01 00:10:29,2023-01-01 00:21:19,1.0,1.43,1.0,N,107,79,1,11.4,1.00,0.5,3.28,0.0,1.0,19.68,2.5,0.00

In [11]:
df_feb2023=pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-02.parquet')

In [12]:
df_feb2023.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
0,1,2023-02-01 00:32:53,2023-02-01 00:34:34,2.0,0.30,1.0,N,142,163,2,4.4,3.50,0.5,0.0,0.0,1.0,9.40,2.5,0.00
1,2,2023-02-01 00:35:16,2023-02-01 00:35:30,1.0,0.00,1.0,N,71,71,4,-3.0,-1.00,-0.5,0.0,0.0,-1.0,-5.50,0.0,0.00
2,2,2023-02-01 00:35:16,2023-02-01 00:35:30,1.0,0.00,1.0,N,71,71,4,3.0,1.00,0.5,0.0,0.0,1.0,5.50,0.0,0.00
3,1,2023-02-01 00:29:33,2023-02-01 01:01:38,0.0,18.80,1.0,N,132,26,1,70.9,2.25,0.5,0.0,0.0,1.0,74.65,0.0,1.25
4,2,2023-02-01 00:12:28,2023-02-01 00:25:46,1.0,3.22,1.0,N,161,145,1,17.0,1.00,0.5,3.3,0.0,1.0,25.30,2.5,0.00

In [13]:
# Q1

In [14]:
print(len(df_jan2023.columns))

19

In [15]:
# Q2

In [16]:
# 1. 计算'duration' 列
df_jan2023['duration'] = (df_jan2023['tpep_dropoff_datetime'] - df_jan2023['tpep_pickup_datetime']).dt.total_seconds() / 60

In [17]:
std_dev = df_jan2023['duration'].std()
print(f"1月份行程时长的标准差为: {std_dev}")

1月份行程时长的标准差为: 42.594351241920904

In [18]:
# Q3

In [19]:
# 2. 筛选出符合条件的记录 (1 <= duration <= 60)
df_filtered = df_jan2023[(df_jan2023['duration'] >= 1) & (df_jan2023['duration'] <= 60)]

# 3. 计算剩余记录的占比
fraction = len(df_filtered) / len(df_jan2023)

print(f"剩余记录的比例为: {fraction:.2%}")

剩余记录的比例为: 98.12%

In [20]:
# Q4

In [21]:
len(df_filtered)

3009173

In [22]:
features = ['PULocationID', 'DOLocationID']
df_filtered[features]

         PULocationID  DOLocationID
0                 161           141
1                  43           237
2                  48           238
3                 138             7
4                 107            79
...               ...           ...
3066761           107            48
3066762           112            75
3066763           114           239
3066764           230            79
3066765           262           143

[3009173 rows x 2 columns]

In [ ]:
from sklearn.feature_extraction import DictVectorizer

# 3. 显式转为字符串，并确保是 Categorical 特征
features = ['PULocationID', 'DOLocationID']
df_filtered[features] = df_filtered[features].astype(str)

# 4. 转为字典列表
train_dicts = df_filtered[features].to_dict(orient='records')

# 5. Fit 向量化器
dv = DictVectorizer()
X_train = dv.fit_transform(train_dicts)

# 6. 查看矩阵维度
print(f"矩阵的维度（列数）: {X_train.shape[1]}")

/tmp/ipykernel_54892/1401009387.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered[features] = df_filtered[features].astype(str)